name: CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

env:
  GOFLAGS: -buildvcs=false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: コードを取得
        uses: actions/checkout@v4

      - name: Goをセットアップ
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: 依存関係を取得
        run: go mod download

      - name: テストを実行
        run: go test ./...
